# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f13355862ef206eb7ae4a72583ad3c6558d097721af0fe02077f0330bdd0319f67535278d72fb713dfa1349ee9bfcf1d1ff29a71658400fc7e235df021ddf96c

test:
  secret_key_base: ba12b6cdc6b099bd8bf66f4543c7c259b76176c53f82443c78caf26a6180959a6f24f2f634a66706ba2adcbec3fd292fc2be86cd260adf871276d97340d97c2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
